name: CICD using maven and SL lab 
on: 
 push: 
   branches: ["master"]
 workflow_dispatch: 
jobs: 
  buildandDeploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Clone the Repo 
      uses: actions/checkout@v4 
    
